[Settings]
ID = "amazing-cray-0a65ff"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  command = “CI= npm run build”

